categories: Temario
search: Buscar
tags: Tags
tagcloud: "Tag Cloud"
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archivos
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: "Recent Posts"
description: Descripción
read_more: "Leer más"
